export function buildDemoCatalog(createStudentId) {
  return [
    {
      id: createStudentId(),
      carnet: "UES-2026-001",
      nombres: "Daniela",
      apellidos: "Rivas",
      edad: 21,
      telefono: "7001-2003",
      direccion: "Colonia El Triunfo, Santa Ana",
      encargado: "Maria Rivas",
      correoInstitucional: "daniela.rivas@ues.edu.sv",
      carrera: "Ingenieria en Desarrollo de Software",
      ciclo: "06",
      promedio: 8.74,
      estado: "Activo",
      fechaRegistro: new Date(Date.now() - 86_400_000).toISOString(),
      latitud: 13.99417,
      longitud: -89.55972,
      ubicacionTexto: "Santa Ana, Santa Ana, El Salvador",
    },
    {
      id: createStudentId(),
      carnet: "UES-2026-002",
      nombres: "Luis",
      apellidos: "Mendez",
      edad: 18,
      telefono: "7110-4412",
      direccion: "Barrio San Sebastian, Sonsonate",
      encargado: "Carlos Mendez",
      correoInstitucional: "luis.mendez@ues.edu.sv",
      carrera: "Arquitectura",
      ciclo: "03",
      promedio: 7.92,
      estado: "Becado",
      fechaRegistro: new Date(Date.now() - 43_200_000).toISOString(),
      latitud: null,
      longitud: null,
      ubicacionTexto: "Sonsonate, El Salvador",
    },
    {
      id: createStudentId(),
      carnet: "UES-2026-003",
      nombres: "Andrea",
      apellidos: "Gonzalez",
      edad: 24,
      telefono: "7288-0041",
      direccion: "Residencial Nueva Esperanza, Ahuachapan",
      encargado: "Rosa Gonzalez",
      correoInstitucional: "andrea.gonzalez@ues.edu.sv",
      carrera: "Administracion de Empresas",
      ciclo: "08",
      promedio: 9.12,
      estado: "Egresado",
      fechaRegistro: new Date().toISOString(),
      latitud: 13.92139,
      longitud: -89.845,
      ubicacionTexto: "Ahuachapan, El Salvador",
    },
  ];
}
